const copy = {
  en: {
    profileTab: "Profile", plannerTab: "Meal planner", profileSettings: "Profile settings", settingsDesc: "Manage the details shown on your profile.",
    displayName: "Display name", aboutYou: "About you", optional: "optional", aboutPlaceholder: "For example: Home economics student who enjoys sharing family recipes.", saveChanges: "Save changes", saving: "Saving…", profileSaved: "Profile saved.",
    contributions: "Your contributions", contributionsDesc: "Recipes and adaptations shared by you.", noContributions: "No contributions yet", contributionsEmpty: "Recipes and adaptations you share will appear here.", recipe: "Recipe", adaptation: "Adaptation", recentItems: "Showing your 6 most recent contributions",
    accountUsername: "Account username", copy: "Copy", copied: "Copied", signInAgain: "Use this username with your password to sign in again.",
    plannerTitle: "Meal planner", plannerDescription: "Choose a recipe or local adaptation, set a cooking date, and add a note.", chooseMeal: "Recipe or adaptation", chooseMealPlaceholder: "Choose what you want to cook", plannedDate: "Cooking date", note: "Notes", notePlaceholder: "Ingredients to buy, budget, or prep reminders…", addToPlan: "Add to meal plan", adding: "Adding…", loadingPlans: "Loading your meal plan…", noPlans: "Nothing planned yet", noPlansDesc: "Choose a recipe, date, and optional note to plan a meal at home.", planned: "Planned", remove: "Remove", savedRecipes: "Saved recipes", browseRecipes: "Browse recipes", yourPlan: "Your planned meals", noteLabel: "Note", recipeOption: "Recipe", adaptationOption: "Local adaptation",
    aboutUs: "About us", aboutTitle: "Good food ideas, made local.", aboutIntro: "WorldPlate Culina brings people together to share recipes, adapt dishes with local ingredients, and make everyday meal planning easier.", aboutRecipesTitle: "Share recipes", aboutRecipes: "Pass along family favorites, traditional dishes, and recipes you have created.", aboutAdaptTitle: "Adapt with local food", aboutAdapt: "Share how recipes from other places can work with ingredients and budgets in your community.", aboutStudentsTitle: "Learn and contribute", aboutStudents: "Students, including Home Economics learners, can share their work and learn from community recipes.", aboutBudgetTitle: "Plan everyday meals", aboutBudget: "Save recipes and add dates or notes to plan what to cook at home and make the next meal easier to decide.", aboutEveryone: "Everyone can explore and contribute. Choose what interests you and take part in the ways that work for you.",
  },
  fil: {
    profileTab: "Profile", plannerTab: "Meal planner", profileSettings: "Mga setting ng profile", settingsDesc: "Pamahalaan ang mga detalyeng ipinapakita sa iyong profile.",
    displayName: "Pangalan na ipapakita", aboutYou: "Tungkol sa iyo", optional: "opsyonal", aboutPlaceholder: "Halimbawa: Estudyante sa Home Economics na mahilig magbahagi ng mga recipe ng pamilya.", saveChanges: "I-save ang mga pagbabago", saving: "Sine-save…", profileSaved: "Na-save ang profile.",
    contributions: "Mga ambag mo", contributionsDesc: "Mga recipe at adaptasyong ibinahagi mo.", noContributions: "Wala pang ambag", contributionsEmpty: "Lalabas dito ang mga recipe at adaptation na ibabahagi mo.", recipe: "Recipe", adaptation: "Adaptation", recentItems: "Ipinapakita ang 6 pinakabagong ambag",
    accountUsername: "Username ng account", copy: "Kopyahin", copied: "Nakopya", signInAgain: "Gamitin ang username na ito at password para mag-sign in muli.",
    plannerTitle: "Meal planner", plannerDescription: "Pumili ng recipe o local adaptation, petsa ng pagluluto, at magdagdag ng tala.", chooseMeal: "Recipe o adaptation", chooseMealPlaceholder: "Piliin ang gusto mong lutuin", plannedDate: "Petsa ng pagluluto", note: "Mga tala", notePlaceholder: "Mga bibilhing sangkap, badyet, o paalala…", addToPlan: "Idagdag sa meal plan", adding: "Idinadagdag…", loadingPlans: "Kinukuha ang meal plan…", noPlans: "Wala pang nakaplanong lutuin", noPlansDesc: "Pumili ng recipe, petsa, at opsyonal na tala para magplano ng lulutuin sa bahay.", planned: "Nakaiskedyul", remove: "Alisin", savedRecipes: "Mga naka-save na recipe", browseRecipes: "Mag-browse ng mga recipe", yourPlan: "Mga nakaplanong pagkain", noteLabel: "Tala", recipeOption: "Recipe", adaptationOption: "Local adaptation",
    aboutUs: "Tungkol sa amin", aboutTitle: "Mas masarap na ideya, iniangkop sa lokal.", aboutIntro: "Pinag-uugnay ng WorldPlate Culina ang mga tao para magbahagi ng recipe, iangkop ang putahe sa lokal na sangkap, at gawing mas madali ang pagpaplano ng pagkain.", aboutRecipesTitle: "Magbahagi ng recipe", aboutRecipes: "Ibahagi ang paborito ng pamilya, tradisyonal na putahe, at sarili mong mga recipe.", aboutAdaptTitle: "Iangkop sa lokal na pagkain", aboutAdapt: "Ibahagi kung paano ihanda ang mga recipe mula sa ibang lugar gamit ang sangkap at badyet sa inyong komunidad.", aboutStudentsTitle: "Matuto at mag-ambag", aboutStudents: "Maaaring magbahagi ng mga proyekto at matuto sa mga recipe ng komunidad ang mga estudyante, kabilang ang mga nag-aaral ng Home Economics.", aboutBudgetTitle: "Magplano ng pang-araw-araw na pagkain", aboutBudget: "Mag-save ng recipe at magtakda ng petsa o tala para mapagplanuhan ang lulutuin sa bahay.", aboutEveryone: "Lahat ay puwedeng tumuklas at mag-ambag. Piliin ang kinahihiligan mo at makilahok sa paraang gusto mo.",
  },
  ja: {
    profileTab: "プロフィール", plannerTab: "献立カレンダー", profileSettings: "プロフィール設定", settingsDesc: "プロフィールに表示する情報を管理します。", displayName: "表示名", aboutYou: "自己紹介", optional: "任意", aboutPlaceholder: "例：家庭料理を共有するのが好きな学生です。", saveChanges: "変更を保存", saving: "保存中…", profileSaved: "プロフィールを保存しました。", contributions: "あなたの投稿", contributionsDesc: "あなたが共有したレシピとアレンジ。", noContributions: "投稿はまだありません", contributionsEmpty: "共有したレシピやアレンジがここに表示されます。", recipe: "レシピ", adaptation: "アレンジ", recentItems: "最近の投稿6件を表示", accountUsername: "アカウント名", copy: "コピー", copied: "コピー済み", signInAgain: "再ログインにはこの名前とパスワードを使います。", plannerTitle: "献立カレンダー", plannerDescription: "レシピや地域のアレンジを選び、日付とメモを追加します。", chooseMeal: "レシピまたはアレンジ", chooseMealPlaceholder: "作りたい料理を選択", plannedDate: "調理日", note: "メモ", notePlaceholder: "買う食材、予算、準備のメモ…", addToPlan: "献立に追加", adding: "追加中…", loadingPlans: "献立を読み込み中…", noPlans: "予定はまだありません", noPlansDesc: "レシピと日付を選んで、家で作る料理を計画しましょう。", planned: "予定", remove: "削除", savedRecipes: "保存したレシピ", browseRecipes: "レシピを見る", yourPlan: "予定した料理", noteLabel: "メモ", recipeOption: "レシピ", adaptationOption: "地域のアレンジ", aboutUs: "私たちについて", aboutTitle: "地域に合わせた、おいしいアイデア。", aboutIntro: "WorldPlate Culinaは、レシピの共有、地元の食材を使ったアレンジ、毎日の献立づくりをつなぐコミュニティです。", aboutRecipesTitle: "レシピを共有", aboutRecipes: "家庭の定番料理や伝統料理、自分で考えたレシピを共有しましょう。", aboutAdaptTitle: "地元の食材でアレンジ", aboutAdapt: "各地の料理を、地域で手に入る食材や予算に合わせる方法を共有します。", aboutStudentsTitle: "学び、参加する", aboutStudents: "家庭科を学ぶ学生も、料理を共有し、コミュニティから学べます。", aboutBudgetTitle: "毎日の献立を計画", aboutBudget: "レシピを保存し、日付やメモを追加して家で作る料理を計画できます。", aboutEveryone: "誰でも閲覧や投稿ができます。興味のあることから自由に参加してください。",
  },
  ar: {
    profileTab: "الملف الشخصي", plannerTab: "مخطط الوجبات", profileSettings: "إعدادات الملف الشخصي", settingsDesc: "أدر التفاصيل التي تظهر في ملفك الشخصي.", displayName: "الاسم المعروض", aboutYou: "نبذة عنك", optional: "اختياري", aboutPlaceholder: "مثال: طالب يحب مشاركة وصفات العائلة.", saveChanges: "حفظ التغييرات", saving: "جارٍ الحفظ…", profileSaved: "تم حفظ الملف الشخصي.", contributions: "مساهماتك", contributionsDesc: "الوصفات والتعديلات التي شاركتها.", noContributions: "لا توجد مساهمات بعد", contributionsEmpty: "ستظهر وصفاتك وتعديلاتك هنا.", recipe: "وصفة", adaptation: "تعديل محلي", recentItems: "عرض آخر 6 مساهمات", accountUsername: "اسم المستخدم", copy: "نسخ", copied: "تم النسخ", signInAgain: "استخدم اسم المستخدم وكلمة المرور لتسجيل الدخول مجددًا.", plannerTitle: "مخطط الوجبات", plannerDescription: "اختر وصفة أو تعديلًا محليًا وحدد تاريخ الطهي وأضف ملاحظة.", chooseMeal: "الوصفة أو التعديل", chooseMealPlaceholder: "اختر ما تريد طهيه", plannedDate: "تاريخ الطهي", note: "ملاحظات", notePlaceholder: "مكونات للشراء أو الميزانية أو تذكيرات التحضير…", addToPlan: "أضف إلى الخطة", adding: "جارٍ الإضافة…", loadingPlans: "جارٍ تحميل خطتك…", noPlans: "لا توجد وجبات مخططة", noPlansDesc: "اختر وصفة وتاريخًا للتخطيط لوجبة في المنزل.", planned: "مخطط", remove: "إزالة", savedRecipes: "الوصفات المحفوظة", browseRecipes: "تصفح الوصفات", yourPlan: "وجباتك المخططة", noteLabel: "ملاحظة", recipeOption: "وصفة", adaptationOption: "تعديل محلي", aboutUs: "من نحن", aboutTitle: "أفكار طعام جيدة بلمسة محلية.", aboutIntro: "يجمع WorldPlate Culina الناس لمشاركة الوصفات وتكييفها مع المكونات المحلية وتسهيل تخطيط الوجبات اليومية.", aboutRecipesTitle: "شارك الوصفات", aboutRecipes: "شارك أطباق العائلة والوصفات التقليدية وما ابتكرته بنفسك.", aboutAdaptTitle: "كيّف الطعام محليًا", aboutAdapt: "شارك طرق إعداد وصفات من بلدان أخرى بمكونات وميزانيات مجتمعك.", aboutStudentsTitle: "تعلّم وساهم", aboutStudents: "يمكن للطلاب، بما في ذلك طلاب الاقتصاد المنزلي، مشاركة أعمالهم والتعلم من وصفات المجتمع.", aboutBudgetTitle: "خطط لوجباتك اليومية", aboutBudget: "احفظ الوصفات وأضف تواريخ وملاحظات لتسهيل التخطيط للطهي في المنزل.", aboutEveryone: "يمكن للجميع الاستكشاف والمساهمة. اختر ما يهمك وشارك بالطريقة المناسبة لك.",
  },
  ko: {
    profileTab: "프로필", plannerTab: "식단 달력", profileSettings: "프로필 설정", settingsDesc: "프로필에 표시할 정보를 관리하세요.", displayName: "표시 이름", aboutYou: "소개", optional: "선택 사항", aboutPlaceholder: "예: 가족 레시피를 나누는 것을 좋아하는 학생", saveChanges: "변경 사항 저장", saving: "저장 중…", profileSaved: "프로필을 저장했습니다.", contributions: "내 기여", contributionsDesc: "내가 공유한 레시피와 현지화 요리", noContributions: "아직 기여한 내용이 없습니다", contributionsEmpty: "공유한 레시피와 현지화 요리가 여기에 표시됩니다.", recipe: "레시피", adaptation: "현지화", recentItems: "최근 기여 6개 표시", accountUsername: "계정 이름", copy: "복사", copied: "복사됨", signInAgain: "다시 로그인할 때 이 이름과 비밀번호를 사용하세요.", plannerTitle: "식단 달력", plannerDescription: "레시피나 현지화 요리를 고르고 날짜와 메모를 추가하세요.", chooseMeal: "레시피 또는 현지화 요리", chooseMealPlaceholder: "요리할 음식을 선택하세요", plannedDate: "요리 날짜", note: "메모", notePlaceholder: "살 재료, 예산, 준비 메모…", addToPlan: "식단에 추가", adding: "추가 중…", loadingPlans: "식단을 불러오는 중…", noPlans: "아직 계획한 식사가 없습니다", noPlansDesc: "레시피와 날짜를 골라 집에서 만들 음식을 계획하세요.", planned: "예정", remove: "삭제", savedRecipes: "저장한 레시피", browseRecipes: "레시피 둘러보기", yourPlan: "계획한 식사", noteLabel: "메모", recipeOption: "레시피", adaptationOption: "현지화 요리", aboutUs: "소개", aboutTitle: "지역에 맞는 맛있는 아이디어.", aboutIntro: "WorldPlate Culina는 레시피 공유, 지역 식재료에 맞춘 요리법, 매일의 식사 계획을 함께합니다.", aboutRecipesTitle: "레시피 공유", aboutRecipes: "가족이 즐겨 먹는 음식과 전통 요리, 직접 만든 레시피를 나누세요.", aboutAdaptTitle: "지역 음식으로 조정", aboutAdapt: "다른 지역의 요리를 우리 지역의 재료와 예산에 맞추는 방법을 공유하세요.", aboutStudentsTitle: "배우고 기여하기", aboutStudents: "가정경제학을 공부하는 학생도 과제를 공유하고 커뮤니티 레시피에서 배울 수 있습니다.", aboutBudgetTitle: "매일의 식사 계획", aboutBudget: "레시피를 저장하고 날짜와 메모를 추가해 집에서 만들 음식을 계획하세요.", aboutEveryone: "누구나 둘러보고 기여할 수 있습니다. 관심 있는 방식으로 참여하세요.",
  },
  zh: {
    profileTab: "个人资料", plannerTab: "用餐计划", profileSettings: "个人资料设置", settingsDesc: "管理个人资料中显示的信息。", displayName: "显示名称", aboutYou: "关于你", optional: "可选", aboutPlaceholder: "例如：喜欢分享家常菜谱的学生。", saveChanges: "保存更改", saving: "正在保存…", profileSaved: "个人资料已保存。", contributions: "你的分享", contributionsDesc: "你分享的食谱和本地改编。", noContributions: "还没有分享内容", contributionsEmpty: "你分享的食谱和改编会显示在这里。", recipe: "食谱", adaptation: "改编", recentItems: "显示最近 6 项分享", accountUsername: "账户用户名", copy: "复制", copied: "已复制", signInAgain: "再次登录时使用此用户名和密码。", plannerTitle: "用餐计划", plannerDescription: "选择食谱或本地改编，设置烹饪日期并添加备注。", chooseMeal: "食谱或改编", chooseMealPlaceholder: "选择想做的菜", plannedDate: "烹饪日期", note: "备注", notePlaceholder: "待买食材、预算或准备提醒…", addToPlan: "添加到计划", adding: "正在添加…", loadingPlans: "正在加载计划…", noPlans: "还没有计划的餐食", noPlansDesc: "选择食谱和日期，计划在家烹饪的餐食。", planned: "已计划", remove: "移除", savedRecipes: "已保存的食谱", browseRecipes: "浏览食谱", yourPlan: "计划中的餐食", noteLabel: "备注", recipeOption: "食谱", adaptationOption: "本地改编", aboutUs: "关于我们", aboutTitle: "让美味点子融入本地生活。", aboutIntro: "WorldPlate Culina 汇聚人们分享食谱、用本地食材改编菜肴，并轻松规划日常餐食。", aboutRecipesTitle: "分享食谱", aboutRecipes: "分享家庭喜爱的菜肴、传统美食和原创食谱。", aboutAdaptTitle: "用本地食材改编", aboutAdapt: "分享如何用社区可获得的食材和预算制作世界各地的菜肴。", aboutStudentsTitle: "学习并分享", aboutStudents: "包括家政学生在内的学生可以分享作品并从社区食谱中学习。", aboutBudgetTitle: "规划日常餐食", aboutBudget: "保存食谱并添加日期或备注，计划在家做什么菜。", aboutEveryone: "每个人都可以探索和分享。选择感兴趣的内容，自由参与。",
  },
  it: {
    profileTab: "Profilo", plannerTab: "Piano pasti", profileSettings: "Impostazioni profilo", settingsDesc: "Gestisci i dettagli mostrati nel tuo profilo.", displayName: "Nome visualizzato", aboutYou: "Chi sei", optional: "facoltativo", aboutPlaceholder: "Per esempio: Studente appassionato di ricette di famiglia.", saveChanges: "Salva modifiche", saving: "Salvataggio…", profileSaved: "Profilo salvato.", contributions: "I tuoi contributi", contributionsDesc: "Ricette e adattamenti che hai condiviso.", noContributions: "Nessun contributo", contributionsEmpty: "Le ricette e gli adattamenti condivisi appariranno qui.", recipe: "Ricetta", adaptation: "Adattamento", recentItems: "Ultimi 6 contributi", accountUsername: "Nome utente", copy: "Copia", copied: "Copiato", signInAgain: "Usa questo nome utente e la password per accedere di nuovo.", plannerTitle: "Piano pasti", plannerDescription: "Scegli una ricetta o un adattamento, imposta la data e aggiungi una nota.", chooseMeal: "Ricetta o adattamento", chooseMealPlaceholder: "Scegli cosa cucinare", plannedDate: "Data di preparazione", note: "Note", notePlaceholder: "Ingredienti da comprare, budget o promemoria…", addToPlan: "Aggiungi al piano", adding: "Aggiunta…", loadingPlans: "Caricamento del piano…", noPlans: "Nessun pasto in programma", noPlansDesc: "Scegli una ricetta e una data per pianificare un pasto a casa.", planned: "In programma", remove: "Rimuovi", savedRecipes: "Ricette salvate", browseRecipes: "Sfoglia ricette", yourPlan: "I tuoi pasti", noteLabel: "Nota", recipeOption: "Ricetta", adaptationOption: "Adattamento locale", aboutUs: "Chi siamo", aboutTitle: "Buone idee, con ingredienti locali.", aboutIntro: "WorldPlate Culina unisce le persone per condividere ricette, adattare i piatti agli ingredienti locali e pianificare i pasti quotidiani.", aboutRecipesTitle: "Condividi ricette", aboutRecipes: "Condividi piatti di famiglia, ricette tradizionali e le tue creazioni.", aboutAdaptTitle: "Adatta con ingredienti locali", aboutAdapt: "Condividi come preparare ricette di altri luoghi con ingredienti e budget locali.", aboutStudentsTitle: "Impara e contribuisci", aboutStudents: "Anche gli studenti di economia domestica possono condividere i propri lavori e imparare dalla comunità.", aboutBudgetTitle: "Pianifica i pasti quotidiani", aboutBudget: "Salva ricette e aggiungi date e note per decidere cosa cucinare a casa.", aboutEveryone: "Tutti possono esplorare e contribuire. Scegli ciò che ti interessa.",
  },
  th: {
    profileTab: "โปรไฟล์", plannerTab: "ปฏิทินวางแผนอาหาร", profileSettings: "ตั้งค่าโปรไฟล์", settingsDesc: "จัดการข้อมูลที่แสดงในโปรไฟล์ของคุณ", displayName: "ชื่อที่แสดง", aboutYou: "เกี่ยวกับคุณ", optional: "ไม่บังคับ", aboutPlaceholder: "เช่น นักเรียนที่ชอบแบ่งปันสูตรอาหารครอบครัว", saveChanges: "บันทึกการเปลี่ยนแปลง", saving: "กำลังบันทึก…", profileSaved: "บันทึกโปรไฟล์แล้ว", contributions: "ผลงานของคุณ", contributionsDesc: "สูตรอาหารและการดัดแปลงที่คุณแบ่งปัน", noContributions: "ยังไม่มีผลงาน", contributionsEmpty: "สูตรอาหารและการดัดแปลงที่คุณแบ่งปันจะแสดงที่นี่", recipe: "สูตรอาหาร", adaptation: "การดัดแปลง", recentItems: "แสดงผลงานล่าสุด 6 รายการ", accountUsername: "ชื่อผู้ใช้บัญชี", copy: "คัดลอก", copied: "คัดลอกแล้ว", signInAgain: "ใช้ชื่อผู้ใช้นี้และรหัสผ่านเพื่อเข้าสู่ระบบอีกครั้ง", plannerTitle: "ปฏิทินวางแผนอาหาร", plannerDescription: "เลือกสูตรหรือการดัดแปลงในท้องถิ่น กำหนดวันทำอาหาร และเพิ่มบันทึก", chooseMeal: "สูตรหรือการดัดแปลง", chooseMealPlaceholder: "เลือกเมนูที่ต้องการทำ", plannedDate: "วันที่ทำอาหาร", note: "บันทึก", notePlaceholder: "วัตถุดิบที่ต้องซื้อ งบประมาณ หรือสิ่งที่ต้องเตรียม…", addToPlan: "เพิ่มในแผนอาหาร", adding: "กำลังเพิ่ม…", loadingPlans: "กำลังโหลดแผนอาหาร…", noPlans: "ยังไม่มีแผนอาหาร", noPlansDesc: "เลือกสูตรและวันที่เพื่อวางแผนมื้ออาหารที่บ้าน", planned: "วางแผนแล้ว", remove: "นำออก", savedRecipes: "สูตรอาหารที่บันทึกไว้", browseRecipes: "ดูสูตรอาหาร", yourPlan: "มื้ออาหารที่วางแผนไว้", noteLabel: "บันทึก", recipeOption: "สูตรอาหาร", adaptationOption: "การดัดแปลงท้องถิ่น", aboutUs: "เกี่ยวกับเรา", aboutTitle: "ไอเดียอาหารดี ๆ ที่ปรับให้เข้ากับท้องถิ่น", aboutIntro: "WorldPlate Culina เชื่อมผู้คนเพื่อแบ่งปันสูตรอาหาร ปรับเมนูด้วยวัตถุดิบท้องถิ่น และวางแผนมื้ออาหารประจำวัน", aboutRecipesTitle: "แบ่งปันสูตรอาหาร", aboutRecipes: "แบ่งปันเมนูโปรดของครอบครัว อาหารดั้งเดิม และสูตรที่คุณคิดขึ้นเอง", aboutAdaptTitle: "ปรับสูตรด้วยอาหารท้องถิ่น", aboutAdapt: "แบ่งปันวิธีทำอาหารจากที่อื่นด้วยวัตถุดิบและงบประมาณในชุมชนของคุณ", aboutStudentsTitle: "เรียนรู้และร่วมแบ่งปัน", aboutStudents: "นักเรียน รวมถึงผู้เรียนคหกรรมศาสตร์ สามารถแบ่งปันผลงานและเรียนรู้จากสูตรของชุมชน", aboutBudgetTitle: "วางแผนมื้ออาหารประจำวัน", aboutBudget: "บันทึกสูตรและเพิ่มวันที่หรือโน้ตเพื่อวางแผนว่าจะทำอะไรที่บ้าน", aboutEveryone: "ทุกคนสำรวจและแบ่งปันได้ เลือกสิ่งที่สนใจและมีส่วนร่วมได้ตามต้องการ",
  },
  hi: {
    profileTab: "प्रोफ़ाइल", plannerTab: "भोजन योजना", profileSettings: "प्रोफ़ाइल सेटिंग्स", settingsDesc: "अपनी प्रोफ़ाइल में दिखने वाली जानकारी प्रबंधित करें।", displayName: "दिखने वाला नाम", aboutYou: "आपके बारे में", optional: "वैकल्पिक", aboutPlaceholder: "उदाहरण: परिवार की रेसिपी साझा करने वाला छात्र।", saveChanges: "बदलाव सहेजें", saving: "सहेजा जा रहा है…", profileSaved: "प्रोफ़ाइल सहेजी गई।", contributions: "आपके योगदान", contributionsDesc: "आपकी साझा की गई रेसिपी और स्थानीय रूपांतर।", noContributions: "अभी कोई योगदान नहीं", contributionsEmpty: "आपकी साझा की गई रेसिपी और रूपांतर यहाँ दिखेंगे।", recipe: "रेसिपी", adaptation: "स्थानीय रूपांतर", recentItems: "हाल के 6 योगदान दिखाए जा रहे हैं", accountUsername: "खाता उपयोगकर्ता नाम", copy: "कॉपी करें", copied: "कॉपी हो गया", signInAgain: "दोबारा साइन इन करने के लिए यह नाम और पासवर्ड इस्तेमाल करें।", plannerTitle: "भोजन योजना", plannerDescription: "रेसिपी या स्थानीय रूपांतर चुनें, तारीख तय करें और नोट जोड़ें।", chooseMeal: "रेसिपी या रूपांतर", chooseMealPlaceholder: "बनाने के लिए चुनें", plannedDate: "खाना बनाने की तारीख", note: "नोट्स", notePlaceholder: "खरीदने की सामग्री, बजट या तैयारी के रिमाइंडर…", addToPlan: "योजना में जोड़ें", adding: "जोड़ा जा रहा है…", loadingPlans: "भोजन योजना लोड हो रही है…", noPlans: "अभी कोई भोजन तय नहीं", noPlansDesc: "घर पर भोजन की योजना के लिए रेसिपी और तारीख चुनें।", planned: "तय", remove: "हटाएँ", savedRecipes: "सहेजी गई रेसिपी", browseRecipes: "रेसिपी देखें", yourPlan: "आपके तय भोजन", noteLabel: "नोट", recipeOption: "रेसिपी", adaptationOption: "स्थानीय रूपांतर", aboutUs: "हमारे बारे में", aboutTitle: "स्वादिष्ट विचार, स्थानीय अंदाज़ में।", aboutIntro: "WorldPlate Culina रेसिपी साझा करने, स्थानीय सामग्री से व्यंजन ढालने और रोज़ के भोजन की योजना बनाने के लिए लोगों को जोड़ता है।", aboutRecipesTitle: "रेसिपी साझा करें", aboutRecipes: "परिवार के पसंदीदा, पारंपरिक व्यंजन और अपनी बनाई रेसिपी साझा करें।", aboutAdaptTitle: "स्थानीय सामग्री से ढालें", aboutAdapt: "दूसरी जगहों की रेसिपी को स्थानीय सामग्री और बजट से बनाने के तरीके साझा करें।", aboutStudentsTitle: "सीखें और योगदान दें", aboutStudents: "गृह अर्थशास्त्र के विद्यार्थियों सहित छात्र अपना काम साझा कर सकते हैं और समुदाय से सीख सकते हैं।", aboutBudgetTitle: "रोज़ के भोजन की योजना", aboutBudget: "रेसिपी सहेजें और घर पर पकाने के लिए तारीख व नोट जोड़ें।", aboutEveryone: "हर कोई खोज सकता है और योगदान दे सकता है। अपनी रुचि के अनुसार जुड़ें।",
  },
  fr: {
    profileTab: "Profil", plannerTab: "Planning des repas", profileSettings: "Paramètres du profil", settingsDesc: "Gérez les informations affichées sur votre profil.", displayName: "Nom affiché", aboutYou: "À propos de vous", optional: "facultatif", aboutPlaceholder: "Ex. : Étudiant qui aime partager des recettes familiales.", saveChanges: "Enregistrer", saving: "Enregistrement…", profileSaved: "Profil enregistré.", contributions: "Vos contributions", contributionsDesc: "Recettes et adaptations que vous avez partagées.", noContributions: "Aucune contribution pour le moment", contributionsEmpty: "Vos recettes et adaptations partagées apparaîtront ici.", recipe: "Recette", adaptation: "Adaptation", recentItems: "Vos 6 contributions les plus récentes", accountUsername: "Nom d’utilisateur", copy: "Copier", copied: "Copié", signInAgain: "Utilisez ce nom et votre mot de passe pour vous reconnecter.", plannerTitle: "Planning des repas", plannerDescription: "Choisissez une recette ou une adaptation locale, une date et une note.", chooseMeal: "Recette ou adaptation", chooseMealPlaceholder: "Choisissez un plat", plannedDate: "Date de préparation", note: "Notes", notePlaceholder: "Ingrédients à acheter, budget ou rappels…", addToPlan: "Ajouter au planning", adding: "Ajout…", loadingPlans: "Chargement du planning…", noPlans: "Aucun repas prévu", noPlansDesc: "Choisissez une recette et une date pour planifier un repas à la maison.", planned: "Prévu", remove: "Supprimer", savedRecipes: "Recettes enregistrées", browseRecipes: "Parcourir les recettes", yourPlan: "Vos repas prévus", noteLabel: "Note", recipeOption: "Recette", adaptationOption: "Adaptation locale", aboutUs: "À propos", aboutTitle: "De bonnes idées, adaptées aux ingrédients locaux.", aboutIntro: "WorldPlate Culina rassemble une communauté autour des recettes, des adaptations locales et de la planification des repas du quotidien.", aboutRecipesTitle: "Partager des recettes", aboutRecipes: "Partagez des plats familiaux, des recettes traditionnelles et vos créations.", aboutAdaptTitle: "Adapter avec des produits locaux", aboutAdapt: "Montrez comment cuisiner des plats d’ailleurs avec les ingrédients et le budget de votre région.", aboutStudentsTitle: "Apprendre et contribuer", aboutStudents: "Les étudiants, notamment en économie familiale, peuvent partager leurs travaux et apprendre de la communauté.", aboutBudgetTitle: "Prévoir les repas du quotidien", aboutBudget: "Enregistrez des recettes et ajoutez des dates ou des notes pour planifier les repas à la maison.", aboutEveryone: "Tout le monde peut explorer et contribuer. Choisissez ce qui vous intéresse.",
  },
  "es-MX": {
    profileTab: "Perfil", plannerTab: "Planificador de comidas", profileSettings: "Ajustes del perfil", settingsDesc: "Administra la información que aparece en tu perfil.", displayName: "Nombre para mostrar", aboutYou: "Acerca de ti", optional: "opcional", aboutPlaceholder: "Por ejemplo: Estudiante que disfruta compartir recetas familiares.", saveChanges: "Guardar cambios", saving: "Guardando…", profileSaved: "Perfil guardado.", contributions: "Tus aportaciones", contributionsDesc: "Recetas y adaptaciones que compartiste.", noContributions: "Aún no hay aportaciones", contributionsEmpty: "Aquí aparecerán las recetas y adaptaciones que compartas.", recipe: "Receta", adaptation: "Adaptación", recentItems: "Mostrando tus 6 aportaciones más recientes", accountUsername: "Usuario de la cuenta", copy: "Copiar", copied: "Copiado", signInAgain: "Usa este usuario y tu contraseña para volver a iniciar sesión.", plannerTitle: "Planificador de comidas", plannerDescription: "Elige una receta o adaptación local, una fecha y agrega una nota.", chooseMeal: "Receta o adaptación", chooseMealPlaceholder: "Elige qué quieres cocinar", plannedDate: "Fecha para cocinar", note: "Notas", notePlaceholder: "Ingredientes por comprar, presupuesto o recordatorios…", addToPlan: "Agregar al plan", adding: "Agregando…", loadingPlans: "Cargando el plan…", noPlans: "Aún no hay comidas planeadas", noPlansDesc: "Elige una receta y fecha para planear qué cocinar en casa.", planned: "Planeado", remove: "Quitar", savedRecipes: "Recetas guardadas", browseRecipes: "Explorar recetas", yourPlan: "Tus comidas planeadas", noteLabel: "Nota", recipeOption: "Receta", adaptationOption: "Adaptación local", aboutUs: "Acerca de", aboutTitle: "Buenas ideas, con ingredientes locales.", aboutIntro: "WorldPlate Culina reúne a las personas para compartir recetas, adaptarlas con ingredientes locales y planear las comidas de cada día.", aboutRecipesTitle: "Compartir recetas", aboutRecipes: "Comparte recetas familiares, platillos tradicionales y tus propias creaciones.", aboutAdaptTitle: "Adaptar con ingredientes locales", aboutAdapt: "Comparte cómo preparar recetas de otros lugares con los ingredientes y el presupuesto de tu comunidad.", aboutStudentsTitle: "Aprender y contribuir", aboutStudents: "Los estudiantes, incluidos quienes estudian Economía Doméstica, pueden compartir sus trabajos y aprender de la comunidad.", aboutBudgetTitle: "Planear las comidas de cada día", aboutBudget: "Guarda recetas y agrega fechas o notas para decidir qué cocinar en casa.", aboutEveryone: "Todas las personas pueden explorar y contribuir. Participa en lo que te interese.",
  },
  tr: {
    profileTab: "Profil", plannerTab: "Yemek planı", profileSettings: "Profil ayarları", settingsDesc: "Profilinde görünen bilgileri yönet.", displayName: "Görünen ad", aboutYou: "Hakkında", optional: "isteğe bağlı", aboutPlaceholder: "Örneğin: Aile tariflerini paylaşmayı seven bir öğrenci.", saveChanges: "Değişiklikleri kaydet", saving: "Kaydediliyor…", profileSaved: "Profil kaydedildi.", contributions: "Katkıların", contributionsDesc: "Paylaştığın tarifler ve uyarlamalar.", noContributions: "Henüz katkı yok", contributionsEmpty: "Paylaştığın tarifler ve uyarlamalar burada görünür.", recipe: "Tarif", adaptation: "Uyarlama", recentItems: "Son 6 katkı gösteriliyor", accountUsername: "Hesap kullanıcı adı", copy: "Kopyala", copied: "Kopyalandı", signInAgain: "Tekrar giriş yapmak için bu kullanıcı adını ve şifreni kullan.", plannerTitle: "Yemek planı", plannerDescription: "Bir tarif veya yerel uyarlama seç, tarih ve not ekle.", chooseMeal: "Tarif veya uyarlama", chooseMealPlaceholder: "Pişirmek istediğini seç", plannedDate: "Pişirme tarihi", note: "Notlar", notePlaceholder: "Alınacak malzemeler, bütçe veya hazırlık hatırlatmaları…", addToPlan: "Plana ekle", adding: "Ekleniyor…", loadingPlans: "Plan yükleniyor…", noPlans: "Henüz planlanan yemek yok", noPlansDesc: "Evde pişireceğin yemeği planlamak için tarif ve tarih seç.", planned: "Planlandı", remove: "Kaldır", savedRecipes: "Kaydedilen tarifler", browseRecipes: "Tariflere göz at", yourPlan: "Planladığın yemekler", noteLabel: "Not", recipeOption: "Tarif", adaptationOption: "Yerel uyarlama", aboutUs: "Hakkımızda", aboutTitle: "Yerel malzemelerle güzel yemek fikirleri.", aboutIntro: "WorldPlate Culina; tarif paylaşımı, yerel malzemelerle uyarlama ve günlük yemek planlaması için insanları bir araya getirir.", aboutRecipesTitle: "Tarif paylaş", aboutRecipes: "Aile favorilerini, geleneksel yemekleri ve kendi tariflerini paylaş.", aboutAdaptTitle: "Yerel malzemelerle uyarla", aboutAdapt: "Başka yerlerin tariflerini kendi topluluğundaki malzemeler ve bütçeyle hazırlama yollarını paylaş.", aboutStudentsTitle: "Öğren ve katkıda bulun", aboutStudents: "Ev ekonomisi öğrencileri de çalışmalarını paylaşabilir ve topluluk tariflerinden öğrenebilir.", aboutBudgetTitle: "Günlük yemekleri planla", aboutBudget: "Tarifleri kaydet, evde ne pişireceğini planlamak için tarih ve not ekle.", aboutEveryone: "Herkes keşfedebilir ve katkıda bulunabilir. İlgini çekeni seç.",
  },
};

const common = {
  en: { yourProfile: "Your profile", signOut: "Sign out", saveRecipe: "Save recipe", savedLabel: "Recipe saved", addToMyList: "Add to My List", editBio: "Edit bio", bioEmpty: "Add a short bio to tell the community about yourself.", cancel: "Cancel", copyError: "Couldn't copy your username." },
  fil: { yourProfile: "Iyong profile", signOut: "Mag-sign out", saveRecipe: "I-save ang recipe", savedLabel: "Naka-save na", addToMyList: "Idagdag sa My List", editBio: "I-edit ang bio", bioEmpty: "Magdagdag ng maikling bio para ipakilala ang sarili sa komunidad.", cancel: "Kanselahin", copyError: "Hindi makopya ang username." },
  ja: { yourProfile: "あなたのプロフィール", signOut: "ログアウト", saveRecipe: "レシピを保存", savedLabel: "保存済み", addToMyList: "My Listに追加", editBio: "自己紹介を編集", bioEmpty: "コミュニティに向けて自己紹介を追加しましょう。", cancel: "キャンセル", copyError: "ユーザー名をコピーできませんでした。" },
  ar: { yourProfile: "ملفك الشخصي", signOut: "تسجيل الخروج", saveRecipe: "احفظ الوصفة", savedLabel: "تم الحفظ", addToMyList: "أضف إلى قائمتي", editBio: "تعديل النبذة", bioEmpty: "أضف نبذة قصيرة لتعريف المجتمع بنفسك.", cancel: "إلغاء", copyError: "تعذر نسخ اسم المستخدم." },
  ko: { yourProfile: "내 프로필", signOut: "로그아웃", saveRecipe: "레시피 저장", savedLabel: "저장됨", addToMyList: "내 목록에 추가", editBio: "소개 편집", bioEmpty: "커뮤니티에 나를 소개하는 짧은 글을 추가하세요.", cancel: "취소", copyError: "사용자 이름을 복사할 수 없습니다." },
  zh: { yourProfile: "你的个人资料", signOut: "退出登录", saveRecipe: "保存食谱", savedLabel: "已保存", addToMyList: "添加到我的列表", editBio: "编辑简介", bioEmpty: "添加简短介绍，让社区了解你。", cancel: "取消", copyError: "无法复制用户名。" },
  it: { yourProfile: "Il tuo profilo", signOut: "Esci", saveRecipe: "Salva ricetta", savedLabel: "Ricetta salvata", addToMyList: "Aggiungi a My List", editBio: "Modifica bio", bioEmpty: "Aggiungi una breve presentazione per la comunità.", cancel: "Annulla", copyError: "Impossibile copiare il nome utente." },
  th: { yourProfile: "โปรไฟล์ของคุณ", signOut: "ออกจากระบบ", saveRecipe: "บันทึกสูตรอาหาร", savedLabel: "บันทึกแล้ว", addToMyList: "เพิ่มในรายการของฉัน", editBio: "แก้ไขประวัติ", bioEmpty: "เพิ่มประวัติสั้น ๆ เพื่อแนะนำตัวกับชุมชน", cancel: "ยกเลิก", copyError: "คัดลอกชื่อผู้ใช้ไม่ได้" },
  hi: { yourProfile: "आपकी प्रोफ़ाइल", signOut: "साइन आउट", saveRecipe: "रेसिपी सहेजें", savedLabel: "सहेजी गई", addToMyList: "मेरी सूची में जोड़ें", editBio: "बायो संपादित करें", bioEmpty: "समुदाय को अपना परिचय देने के लिए छोटा बायो जोड़ें।", cancel: "रद्द करें", copyError: "उपयोगकर्ता नाम कॉपी नहीं हो सका।" },
  fr: { yourProfile: "Votre profil", signOut: "Se déconnecter", saveRecipe: "Enregistrer la recette", savedLabel: "Recette enregistrée", addToMyList: "Ajouter à Ma liste", editBio: "Modifier la bio", bioEmpty: "Ajoutez une courte présentation pour la communauté.", cancel: "Annuler", copyError: "Impossible de copier le nom d’utilisateur." },
  "es-MX": { yourProfile: "Tu perfil", signOut: "Cerrar sesión", saveRecipe: "Guardar receta", savedLabel: "Receta guardada", addToMyList: "Agregar a Mi lista", editBio: "Editar biografía", bioEmpty: "Agrega una breve presentación para la comunidad.", cancel: "Cancelar", copyError: "No se pudo copiar el usuario." },
  tr: { yourProfile: "Profilin", signOut: "Çıkış yap", saveRecipe: "Tarifi kaydet", savedLabel: "Kaydedildi", addToMyList: "Listeme ekle", editBio: "Biyografiyi düzenle", bioEmpty: "Topluluğa kendini tanıtmak için kısa bir biyografi ekle.", cancel: "İptal", copyError: "Kullanıcı adı kopyalanamadı." },
};

export function profileText(language, key) {
  return copy[language]?.[key] || common[language]?.[key] || copy.en[key] || key;
}
